# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-product' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ios-product

  # Pods for FLutterHybridDemo
  flutter_application_path = '../flutter_widget/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

  target 'ios-productTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-productUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
